version: '3'

services:

  api_php:
    build: ./php
    restart: always
    ports:
      - 81:80
    volumes:
      - $PWD/app:/var/www/html
    links: 
      - api_mysql
    environment:
      - MYSQL_ROOT_PASSWORD
  

  api_mysql:
    image: mysql:5
    restart: always
    ports:
      - 3306:3306
    volumes:
      - $PWD/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
  